# -*- coding: utf-8 -*-
"""Load_data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b2eMJyY2lyKI5uNMh6shn0f0sjjjQWKE
"""



"""# Data Collection"""

!pip install sktime pmdarima statsmodels --upgrade --quiet --use-deprecated=legacy-resolver

!pip install --upgrade pandas

# === System Utilities ===
import os

# === Core Libraries ===
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Response Variable
CPI_df = pd.read_excel('CPIAUCSL.xlsx') #CPI for all urban customers

print(CPI_df)

# Predictor variables
FEDFUNDS_df = pd.read_excel('data/raw/FEDFUNDS(1).xlsx')
GDP_df = pd.read_excel('data/raw/GDPC1(1).xlsx')
M2SL_df = pd.read_excel('data/raw/M2SL(1).xlsx')
M2V_df = pd.read_excel('data/rawM2V9(1).xlsx')
DCOILBRENT_df = pd.read_excel('data/raw/DCOILBRENTEU(1).xlsx')

print(GDP_df)

print(FEDFUNDS_df)

print(M2SL_df)

print(M2V_df)