# -*- coding: utf-8 -*-
"""my_functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15ysiTXZuNtUlyTyyhMbulZxnhvbUyMoT
"""

# Compute a function for missing data percentage
def missing_value_percentage(df):
    missing_count = df.isnull().sum()  # Count of missing values
    total_rows = len(df)  # Total number of rows
    missing_percent = (missing_count / total_rows) * 100  # Percentage calculation

    # Create a DataFrame to display results
    missing_df = pd.DataFrame({'Missing Count': missing_count, 'Missing Percentage': missing_percent})

    # Filter only columns with missing values
    missing_df = missing_df[missing_df['Missing Count'] > 0]
    return missing_df

