# -*- coding: utf-8 -*-
"""Load_data.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b2eMJyY2lyKI5uNMh6shn0f0sjjjQWKE
"""

import pandas as pd

def load_data(file) :
    df = pd.read_excel(file)
    return df